version: '3.8'
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ../redis_data:/data
    command: redis-server /etc/redis/redis.conf
    privileged: true

  meme:
    image: meetwq/meme-generator:latest
    restart: always
    ports:
      - "2233"

volumes:
  mongo_data:
  esdata01:
    driver: local
