version: '3.8'
services:
  front:
    build: ./front-end
    ports:
      - "3000"
    volumes:
      - /usr/src/app/node_modules

  nginx:
    build:
      context: .
      dockerfile: "./conf/Dockerfile.nginx"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx-dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front

