version: '3.8'
services:
  front:
    build: ./front-end
    ports:
      - "3000"
    volumes:
      - /usr/src/app/node_modules

  server:
    restart: on-failure
    build: ./server-end
    ports:
      - "6789"
      - "8888"
    depends_on:
      - logstash
    volumes:
      - ./.env:/root/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf 
      - ../redis_data:/data      
    command: redis-server /etc/redis/redis.conf 
    privileged: true

  meme:
    image: meetwq/meme-generator:latest
    restart: always
    ports:
      - "2233"

  elasticsearch:
    restart: on-failure
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  logstash:
    restart: on-failure
    image: docker.elastic.co/logger_hook/logger_hook:7.10.1
    container_name: logger_hook
    volumes:
      - ./conf/logger_hook.conf:/usr/share/logger_hook/pipeline/logger_hook.conf
    ports:
      - "5001:5001"
    depends_on:
      - elasticsearch

  kibana:
    restart: on-failure
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  nginx:
    build:
      context: .
      dockerfile: "./conf/Dockerfile.nginx"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
      - web

volumes:
  mongo_data:
  esdata01:
    driver: local

