// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	chiwei_bot "github.com/bezhai/chiwei_bot/server-end/biz/router/chiwei_bot"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	chiwei_bot.Register(r)
}
