# 基于官方的 Nginx 镜像
FROM nginx:latest
# 安装 wget 和 dockerize
COPY dockerize-linux-amd64-v0.7.0.tar.gz ./
RUN tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.7.0.tar.gz && \
    rm dockerize-linux-amd64-v0.7.0.tar.gz
# 复制启动脚本
COPY ./conf/start-nginx.sh /start-nginx.sh
# 设置启动脚本的执行权限
RUN chmod +x /start-nginx.sh
# 设置容器启动时运行的命令
CMD ["/start-nginx.sh"]