// Code generated by hertz generator.

package chiwei_bot

import (
	"context"

	conf "github.com/bezhai/chiwei_bot/server-end/biz/model/conf"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetStringValue .
// @router /api/conf/string_value [GET]
func GetStringValue(ctx context.Context, c *app.RequestContext) {
	var err error
	var req conf.GetStringValueRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(conf.GetStringValueResponse)

	c.JSON(consts.StatusOK, resp)
}
